### ISSUE TITLE
the running script for “sequence-to-video generation”

### ISSUE THREAD

**Issue by lu123456789** [damo-vilab/videocomposer#19]
Hello, great work. May I ask when will the running script for “sequence-to-video generation” such as "sketch sequence-to-video generation" and "Compositional depth sequence-to-video generation" be released?
Thanks for your work!

**Comment by lihuining** [comment]
Hello, I have the same question, how did you find it?

**Comment by lu123456789** [comment]
> Hello, I have the same question, how did you find it?

Sorry, I’ve forgotten how I resolved it.  You could try submitting a new issue.
