### ISSUE TITLE
When will the code be fully released? Thank you.

### ISSUE THREAD

**Issue by HUAFOR** [damo-vilab/videocomposer#2]

**Comment by TruthSearcher** [comment]
They don't have a track record for releasing code, so I think it will be held back indefinitely.

**Comment by Steven-SWZhang** [comment]
Hi, thanks for your interest in VideoComposer. We are currently preparing for it and plan to release it within two weeks.

**Comment by rohun-tripathi** [comment]
Hello, was the training code and the full code released?
