### ISSUE TITLE
Question about extracting the different conditions

### ISSUE THREAD

**Issue by YujieOuO** [damo-vilab/videocomposer#38]
Thank you for the great repo.

When i try to run the code with the following command:
python run_net.py \
    --cfg configs/exp01_vidcomposer_full.yaml \
    --input_video "demo_video/blackswan.mp4" \
    --input_text_desc "A black swan swam in the water" \
    --seed 9999

some errors are occurred.
![image](https://github.com/damo-vilab/videocomposer/assets/47097735/62bf8d4b-8827-484f-bfb1-20187817e36e)

It seems that all conditional extractions have failed。
![rank_1-0](https://github.com/damo-vilab/videocomposer/assets/47097735/0572833b-bf11-4c9a-9513-4196b30d8496)

Could you tell me how to fix it ?

**Comment by YujieOuO** [comment]
try other commands:

python run_net.py\
    --cfg configs/exp05_text_depths_wo_style.yaml\
    --seed 9999\
    --input_video demo_video/video_8800.mp4\
    --input_text_desc "A glittering and translucent fish swimming in a small glass bowl with multicolored piece of stone, like a glass fish"

![rank_1-0](https://github.com/damo-vilab/videocomposer/assets/47097735/7689abb9-a287-4a5b-ac9f-047dfbefb722)

The first and second columns still cannot be displayed correctly yet.

**Comment by Steven-SWZhang** [comment]
It seems from the log that you do not have ffmpeg installed.

**Comment by YujieOuO** [comment]
it works, thank you very much.
