### ISSUE TITLE
计算代价询问

### ISSUE THREAD

**Issue by Aopolin-Lv** [damo-vilab/videocomposer#6]
作者你好，看到你们的工作之后感觉非常有意思。请问本工作的训练计算资源要求是什么样的？例如说训练过程需要什么级别的显卡，多少张，训练多久？

**Comment by Steven-SWZhang** [comment]
We recommend using at least 8/16 A100-80G GPUs to fine-tune our model, and the training time depends on the specific task which may take a week or more. We have not yet explored what the minimum data requirement would be if one were to use smaller data to reduce training costs.

**Comment by Aopolin-Lv** [comment]
> We recommend using at least 8/16 A100-80G GPUs to fine-tune our model, and the training time depends on the specific task which may take a week or more. We have not yet explored what the minimum data requirement would be if one were to use smaller data to reduce training costs.

谢谢
